# Generated by Django 5.0.6 on 2024-07-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='click_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
