# Generated by Django 5.0.6 on 2024-07-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_click_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='click_num',
            new_name='likes_num',
        ),
    ]
